version: '3.8'
services:
  frontend-app:
    build:
      context: ../gypsophila_admin_frontend
      dockerfile: ./Dockerfile
    depends_on:
      - backend-app
    ports:
      - '80:80'
    networks:
      - common-network
  backend-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
    networks:
      - common-network
  mysql-container:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - /root/gypsophila-admin/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'j!Y6hTwR'
      TZ: 'Asia/Shanghai'
    networks:
      - common-network
  redis-container:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - /root/gypsophila-admin/docker/redis:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge