version: '3.8'
services:
  frontend-app:
    image: gypsophila/gypsophila_admin_frontend:1.0.2
    depends_on:
      - backend-app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../cert:/cert
    networks:
      - common-network
  backend-app:
    image: gypsophila/gypsophila_admin_backend:1.0.2
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
    networks:
      - common-network
  mysql-container:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - ../docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'j!Y6hTwR'
      TZ: 'Asia/Shanghai'
    networks:
      - common-network
  redis-container:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ../docker/redis:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge