# 运行端口
port: 3000
# mysql 配置
mysql:
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'j!Y6hTwR'
  database: 'gypsophila'
  synchronize: true
# redis 配置
redis:
  host: 'localhost'
  port: 6379
# jwt 密钥
jwt: 
  # 密钥
  secret: 'W9RsC*5zV^sp7*xXG6VY6d#yqn=FNPqA'
  # access_token 过期时间(秒)
  accessExpire: 3000
  # refresh_token 过期时间(秒)
  refreshExpire: 18000