# mysql 配置
mysql:
  host: '127.0.0.1'
  port: 3306
  username: 'root'
  password: 'j!Y6hTwR'
  database: 'gypsophila'
  synchronize: false
# redis 配置
redis:
  host: '127.0.0.1'
  port: 6379
# 运行端口
port: 3000
# jwt 密钥
jwtSecret: 'W9RsC*5zV^sp7*xXG6VY6d#yqn=FNPqA'
# token 过期时间(秒)
tokenExpire:
  accessExpire: 300
  refreshExpire: 1800