# mysql 配置
mysql:
  host: '127.0.0.1'
  port: 3306
  username: 'root'
  password: 'j!Y6hTwR'
  database: 'gypsophila'
  synchronize: false
# 运行端口
port: 3000
# jwt 密钥
jwtSecret: 'W9RsC*5zV^sp7*xXG6VY6d#yqn=FNPqA'
# jwt 密钥过期时间
jwtExpiresIn: '1d'