export const enum ENUM_TASK {
  /** 梦幻西游账号每日金币统计 */
  MHXY_ACCOUNT_GOLD_DAILY = 'MHXY_ACCOUNT_GOLD_DAILY',
  /** 梦幻西游转金待办通知 */
  MHXY_GOLD_TRANSFER_TODO_NOTIFY = 'MHXY_GOLD_TRANSFER_TODO_NOTIFY',
  /** 通知过期检查 */
  NOTICE_EXPIRE_CHECK = 'NOTICE_EXPIRE_CHECK',
}
